path:
  ini: /home/hegwin/Downloads/clients_config.ini
  log_prefix: /home/hegwin/monitor_log/
  schedule: /home/hegwin/schedule.ini

map:
  client:
    PathtoMonitor: PathtoMonitor
    ServerHostIP: ServerHostIP
    ServerHostPort: ServerHostPort
    UserID: UserID
    Password: Password
    TestString: TestString
    SuccessEMailAddress: SuccessEMailAddress
    SuccessEMailText: SuccessEMailText
    FailureEmailAddress: FailureEmailAddress
    TestEmailAddress: TestEmailAddress
    ArchivePath: ArchivePath
    ToBeActionedDirectory: ToBeActionedDirectory
  schedule:
    ClientID: ClientID
    FileType: FileType
    Frequence: Frequence
    ExecuteDate: ExecuteDate
    ExecuteTime: ExecuteTime
    IntervalTime: InvervalTime
    IntervalUnit: IntervalUnit
    StartAt: StartAt
    Status: Status
